spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/peiai
    username: root
    password: 15397610106hh
  data:
    redis:
      host: localhost
      port: 6379

  jackson:
    date-format: yyyy-MM-dd hh:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8888
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
      force-request: true
      force-response: true
# ChatGPT API Key
openai:
  api:
#    key: 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
    key: sk-proj-rBdtDgNim4zL2EklBPEQT3BlbkFJdqH1dh2Gdlza7fHhkeVv
    # ChatGPT API URL
    url: https://api.openai.com/v1/chat/completions
# Proxy Configuration
proxy:
  enabled: true
  host: 127.0.0.1
  port: 10809
# 讯飞星火配置
xunfei:
  client:
    appid: 30c4b5ad
    apiSecret: MjY5MzZkNzdkN2U5MTI0ZWQzNjRlY2I4
    apiKey: b3a7cbdce5acd40fa79092fe748bc96c
#设置图片获取路径的baseURL
#https://mfg8uf6pxn2i.ngrok.xiaomiqiu123.top/uploads/
#http://localhost:8888/uploads/
baseURL: http://localhost:8888/uploads/
